# Generated by Django 4.0.4 on 2022-11-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_image_remove_post_image_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post_pictures'),
        ),
    ]
